spring:
  datasource:
    url: jdbc:mysql://ngMysqlDb:3306/ng_bank
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    sender:
      ngBank@contact.com
    host: NgBankMailServer
    port: 1025
    username: ng
    password: ng
